version: '3.6'
services:
  mtb_portal_vue_frontend:
    build: 
        context: ./vue-frontend
        dockerfile: dockerfile_dev
    ports:
      - "3834:3834"
    environment:
      - NODE_ENV=${NODE_ENV}


