version: '3.6'
services:
  mtb_portal_vue_frontend:
    image: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
    ports:
      - "${CI_FRONTEND_PORT}:${CI_FRONTEND_PORT}"
    environment:
      - NODE_ENV=${CI_NODE_ENV}
      - CI_FRONTEND_PORT
  mtb_portal_flask_backend:
    image: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/backend:${CI_COMMIT_REF_SLUG}"
    volumes:
      - ${CI_VOLUME_MOUNT_PATH_MATRIX}:${CI_VOLUME_MOUNT_PATH_MATRIX}
    ports:
      - "${CI_BACKEND_PORT}:${CI_BACKEND_PORT}"
    environment:
      - CONFIG_FILE_PATH=${CI_CONFIG_FILE_PATH}
      - DB_PASSWORD=topaswp3
      - CI_BACKEND_PORT

