version: '3.6'
 
services:
  mtb_portal_vue_frontend:
    build: 
      context: ./vue-frontend
      args:
        - NODE_ENV=development
        - VUE_APP_API_HOST
  
    image: mtb_portal_vue_frontend
    environment:
        - VUE_APP_API_HOST
        - CI_FRONTEND_PORT
    ports:
      - "${CI_FRONTEND_PORT}:${CI_FRONTEND_PORT}"


