from . import ApiRoutes, PtmNavigatorApiRoutes
import re


def strip_types(flask_route: str):
    """
    Convert Flask-style routes to Vue-style template: <int:id> → :id
    """
    return re.sub(r"<(?:[^:<>]+:)?([^<>]+)>", r":\1", flask_route)


def extract_params(flask_route: str):
    """
    Get parameter names from the route string.
    """
    return re.findall(r"<(?:[^:<>]+:)?([^<>]+)>", flask_route)


def generate_ts_function(name, path):
    params = extract_params(path)

    # Create parameter signature and destructuring
    if params:
        param_signature = "{" + ", ".join(params) + "}"
    else:
        param_signature = ""

    # Convert Flask route to TypeScript template literal
    ts_template = re.sub(
        r"<(?:[^:<>]+:)?([^<>]+)>", lambda m: f"${{{m.group(1)}}}", path
    )

    # Final function line
    if params:
        ts_fn = f"    {name}: ({param_signature}) => `${{API_HOST}}{ts_template}`,"
    else:
        ts_fn = f"    {name}: () => `${{API_HOST}}{ts_template}`,"

    return ts_fn


def generate_ts_file(enum_class):
    lines = [
        "// This file is automatically generated by flask-backend/routes.py, do not make changes here!!!",
        "",
        "const API_HOST = process.env.VUE_APP_API_HOST || '';",
        "",
        "export const api = {",
    ]
    for enum_class in apis:
        for route in enum_class:
            lines.append(generate_ts_function(route.name, route.value))
    lines.append("};")
    return "\n".join(lines)


if __name__ == "__main__":
    apis = [ ApiRoutes, PtmNavigatorApiRoutes ]
    with open("../vue-frontend/src/routes.ts", "w") as f:
        f.write(generate_ts_file(apis))
