from . import utils

TOPAS_LEVEL_MAPPING = {
    utils.DataType.TOPAS_KINASE_SCORE: {
        "data_level": utils.DataType.KINASE_SCORE,
        "scoring_rule_level": utils.DataType.KINASE_SCORE,
    },
    utils.DataType.TOPAS_KINASE_SUBSTRATE: {
        "data_level": utils.DataType.KINASE_SUBSTRATE,
        "scoring_rule_level": utils.DataType.KINASE_SCORE,
    },
    utils.DataType.TOPAS_PHOSPHO_SCORE: {
        "data_level": utils.DataType.PHOSPHO_SCORE,
        "scoring_rule_level": utils.DataType.PHOSPHO_SCORE,
    },
    utils.DataType.TOPAS_PHOSPHO_SCORE_PSITE: {
        "data_level": utils.DataType.PHOSPHO_SCORE_PSITE,
        "scoring_rule_level": utils.DataType.PHOSPHO_SCORE,
    },
    utils.DataType.TOPAS_PROTEIN: {
        "data_level": utils.DataType.FULL_PROTEOME,
        "scoring_rule_level": utils.DataType.FULL_PROTEOME,
    },
}

TOPAS_SCORING_RULES = {
    utils.DataType.FULL_PROTEOME: "highest z-score",
    utils.DataType.PHOSPHO_SCORE: "highest protein phosphorylation score (2nd level z-score, FH)",
    utils.DataType.KINASE_SCORE: "highest kinase score (2nd level z-score, FH)",
}

TOPAS_DIFFERENTIAL_INTENSITY_UNITS = {
    utils.DataType.TOPAS_SCORE: utils.IntensityUnit.SCORE,
    utils.DataType.KINASE_SCORE: utils.IntensityUnit.Z_SCORE,
    utils.DataType.PHOSPHO_SCORE: utils.IntensityUnit.Z_SCORE,
    utils.DataType.FULL_PROTEOME: utils.IntensityUnit.INTENSITY,
    utils.DataType.PHOSPHO_PROTEOME: utils.IntensityUnit.INTENSITY,
    utils.DataType.TRANSCRIPTOMICS: utils.IntensityUnit.INTENSITY,
    utils.DataType.KINASE_SUBSTRATE: utils.IntensityUnit.INTENSITY,
}

# the following topas names should be changed as exception as below to aavoid problems in fronend
TOPAS_RENAMING = {
    "CDK4_6 activity": "CDK4_6_activity",
    "Immune checkpoints": "Immune_checkpoints",
    "Infiltration/Inflammation": "Infiltration_Inflammation",
    "MAPK cascade": "MAPK_cascade",
    "cell cycle": "cell_cycle",
}


IFN_proteins = [
    # this list will be used for on the fly calculation of the TOPAS scores by summing the z_scores
    "MX1",
    "ISG20",
    "ISG15",
    "IFITM3",
    "IFIT5",
    "OAS3",
    "OAS1",
    "OAS2",
    "IRF3",
    "IRF6",
    "IRF1",
    "IRF9",
    "IRF8",
    "IRF2",
    "IRF4",
    "IRF5",
    "STAT1",
    "STAT3",
    "STAT2",
    "MYD88",
    "EIF2AK2",
    "TRIM25",
    "TAP1",
    "IFI35",
    "TAPBP",
    "UBE2L6",
    "TRIM26",
    "SRI",
    "TXNIP",
    "IFITM2",
    "RIPK2",
    "OGFR",
    "ADAR",
    "MVB12A",
    "SAMD9",
    "PLSCR1",
    "NCOA7",
    "IFIH1",
    "TXNIP",
    "EPSTI1",
    "SLC2A1",
    "TYK2",
    "POLR3F",
]


TOPAS_COLORING_RULE = {
    "RTK": "red",
    "TK": "blue",
    "downstream signaling": "green",
    "Developmental": "orange",
    "cell_cycle": "black",
    "Tumor_Antigen": "purple",
}


# TOPAS scores to show on the lolipop plot and the circular plot of the frontside
TOPAS_CATEGORIES = {
    # the rules for the 5th generation
    "ALK": "RTK",
    "AXL": "RTK",
    "DDR1": "RTK",
    "DDR2": "RTK",
    "EGFR": "RTK",
    "ERBB2": "RTK",
    "FGFR1": "RTK",
    "FGFR2": "RTK",
    "FGFR4": "RTK",
    "FLT1": "RTK",
    "FLT4": "RTK",
    "KDR": "RTK",
    "KIT": "RTK",
    "PDGFRA": "RTK",
    "PDGFRB": "RTK",
    "IGF1R": "RTK",
    "EPHA2": "RTK",
    "RET": "RTK",
    "MET": "RTK",
    "Proximal RTK signaling": "downstream signaling",
    "PTK7": "Tumor_Antigen",
    "MAGEA10": "Tumor_Antigen",
    "TACSTD2": "Tumor_Antigen",
    "CEACAM7": "Tumor_Antigen",
    "LRRC15": "Tumor_Antigen",
    "CEACAM1": "Tumor_Antigen",
    "PRAME": "Tumor_Antigen",
    "PROM1": "Tumor_Antigen",
    "GPC3": "Tumor_Antigen",
    "CDH17": "Tumor_Antigen",
    "FAP": "Tumor_Antigen",
    "NECTIN2": "Tumor_Antigen",
    "PMEL": "Tumor_Antigen",
    "F3": "Tumor_Antigen",
    "FOLH1;FOLH1B": "Tumor_Antigen",
    "MAGEA4": "Tumor_Antigen",
    "MSLN": "Tumor_Antigen",
    "SLC39A6": "Tumor_Antigen",
    "FOLR1": "Tumor_Antigen",
    "CTAG1A": "Tumor_Antigen",
    "NECTIN4": "Tumor_Antigen",
    "SLC18A1": "Tumor_Antigen",
    "PSCA": "Tumor_Antigen",
    "CLDN6": "Tumor_Antigen",
    "SLC18A2": "Tumor_Antigen",
    "SSTR2": "Tumor_Antigen",
    "CLDN18-2": "Tumor_Antigen",
    "CTAG2": "Tumor_Antigen",
    "MAGEA3;MAGEA6": "Tumor_Antigen",
    "CD274": "Tumor_Antigen",
}


TOPAS_EXPRESSION_MAPPING = {
    #  the right side is the topas and left side protein
    "ALK": "ALK",
    "AXL": "AXL",
    "DDR1": "DDR1",
    "DDR2": "DDR2",
    "EGFR": "EGFR",
    "ERBB2": "ERBB2",
    "FGFR1": "FGFR1",
    "FGFR2": "FGFR2",
    "FGFR4": "FGFR4",
    "FLT1": "FLT1",
    "FLT4": "FLT4",
    "KDR": "KDR",
    "KIT": "KIT",
    "PDGFRA": "PDGFRA",
    "PDGFRB": "PDGFRB",
    "IGF1R": "IGF1R",
    "EPHA2": "EPHA2",
    "RET": "RET",
    "MET": "MET",
    "ABI1": "Proximal RTK signaling",
    "BCAR1": "Proximal RTK signaling",
    "CAV1": "Proximal RTK signaling",
    "CBL": "Proximal RTK signaling",
    "CRK": "Proximal RTK signaling",
    "CRKL": "Proximal RTK signaling",
    "DOK1": "Proximal RTK signaling",
    "DOK2": "Proximal RTK signaling",
    "DOK3": "Proximal RTK signaling",
    "ELMO2": "Proximal RTK signaling",
    "ERBIN": "Proximal RTK signaling",
    "FRS2": "Proximal RTK signaling",
    "GAB1": "Proximal RTK signaling",
    "GAB2": "Proximal RTK signaling",
    "GRB10": "Proximal RTK signaling",
    "GRB2": "Proximal RTK signaling",
    "GRB7": "Proximal RTK signaling",
    "IRS1": "Proximal RTK signaling",
    "IRS2": "Proximal RTK signaling",
    "NCK1": "Proximal RTK signaling",
    "NCK2": "Proximal RTK signaling",
    "PLCG1": "Proximal RTK signaling",
    "PLCG2": "Proximal RTK signaling",
    "PTK2B": "Proximal RTK signaling",
    "PTPN11": "Proximal RTK signaling",
    "PXN": "Proximal RTK signaling",
    "RACK1": "Proximal RTK signaling",
    "SHANK3": "Proximal RTK signaling",
    "SHB": "Proximal RTK signaling",
    "SHC1": "Proximal RTK signaling",
    "SHC3": "Proximal RTK signaling",
    "SHC4": "Proximal RTK signaling",
    "SOS1": "Proximal RTK signaling",
    "SOS2": "Proximal RTK signaling",
    "TNS3": "Proximal RTK signaling",
    "VAV1": "Proximal RTK signaling",
    "VAV2": "Proximal RTK signaling",
    "STAT1": "Proximal RTK signaling",
    "STAT2": "Proximal RTK signaling",
    "STAT3": "Proximal RTK signaling",
    "STAT4": "Proximal RTK signaling",
    "STAT5A": "Proximal RTK signaling",
    "STAT5B": "Proximal RTK signaling",
    "STAT6": "Proximal RTK signaling",
}
